#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen.

alias afk="gnome-screensaver-command --lock"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Advanced Packaging Tool`

alias apti="sudo apt-get install"
alias aptr="sudo apt-get remove"
alias apts="sudo apt-cache search"
alias aptu="sudo apt-get update \
                && sudo apt-get upgrade"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty trash.

alias empty-trash="rm -rf ~/.local/share/Trash/files/*"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show desktop icons.

alias hide-desktop-icons="gsettings set org.gnome.desktop.background show-desktop-icons false"
alias show-desktop-icons="gsettings set org.gnome.desktop.background show-desktop-icons true"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get local IP.

alias local-ip="ifconfig \
                    | grep 'inet addr' \
                    | grep -v '127.0.0.1' \
                    | cut -d: -f2 \
                    | cut -d' ' -f1"

## - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
## Open from the terminal.
#
#alias o="xdg-open"
#
## - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
## Update applications and CLTs.
#
#alias u="sudo apt-get update \
#            && sudo apt-get upgrade \
#            && npm install -g npm \
#            && npm upgrade -g"

alias remove="sudo apt-get purge --auto-remove"
alias _copy="xclip -selection clipboard"
